# Generated by Django 2.2 on 2021-12-26 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements_app', '0009_auto_20211226_0036'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='categoty_name',
            field=models.CharField(db_index=True, default='', max_length=500, verbose_name='Наименование рубрики'),
        ),
    ]
