# Generated by Django 2.2 on 2021-12-26 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements_app', '0010_advertisement_categoty_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Имя автора')),
                ('mail', models.CharField(db_index=True, max_length=100, verbose_name='Эмаил автора')),
                ('phone', models.IntegerField(db_index=True, default='----------', max_length=11, verbose_name='Телефон')),
            ],
            options={
                'db_table': 'authors',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='advertisement',
            name='author_content',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Author', to='advertisements_app.Author', verbose_name='Автор'),
        ),
    ]
