# Generated by Django 2.2 on 2021-12-26 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements_app', '0011_auto_20211226_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='phone',
            field=models.IntegerField(db_index=True, default='----------', verbose_name='Телефон'),
        ),
    ]
