# Generated by Django 2.2 on 2021-12-26 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements_app', '0012_auto_20211226_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='author_content',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author', to='advertisements_app.Author', verbose_name='Автор'),
        ),
    ]
