# Generated by Django 2.2 on 2021-12-26 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements_app', '0013_auto_20211227_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='mail',
            field=models.CharField(db_index=True, max_length=100, verbose_name='@маил автора'),
        ),
    ]
