# Generated by Django 2.2 on 2022-01-29 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shops', '0004_auto_20220129_0255'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, db_index=True, max_length=15, null=True, verbose_name='Телефон'),
        ),
    ]
