# Generated by Django 2.2 on 2022-01-29 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shops', '0005_profile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, db_index=True, default='', max_length=15, verbose_name='Телефон'),
        ),
    ]
