# Generated by Django 2.2 on 2022-01-29 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shops', '0008_auto_20220129_1718'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, default='Неизвестно', max_length=50, verbose_name='Название')),
                ('adress', models.TextField(db_index=True, default='неизвестно', verbose_name='Адрес')),
                ('tel', models.CharField(db_index=True, default='Неизвестно', max_length=50, verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Магазин',
                'verbose_name_plural': 'Магазины',
                'db_table': 'Shops',
            },
        ),
    ]
