# Generated by Django 2.2 on 2022-01-29 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shops', '0011_purchasehistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_index=True, max_length=40, null=True, verbose_name='наименование')),
                ('description', models.CharField(blank=True, db_index=True, max_length=40, null=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='Дата начало предложения')),
            ],
            options={
                'verbose_name': 'Предложение',
                'verbose_name_plural': 'Предложения',
                'db_table': 'Promotions',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_index=True, max_length=40, null=True, verbose_name='наименование')),
                ('description', models.CharField(blank=True, db_index=True, max_length=40, null=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='Дата начало акции')),
            ],
            options={
                'verbose_name': 'Акция',
                'verbose_name_plural': 'Акции',
                'db_table': 'Stock',
            },
        ),
        migrations.AlterModelOptions(
            name='purchasehistory',
            options={'verbose_name': 'История с товарами', 'verbose_name_plural': 'истории с товарами'},
        ),
        migrations.AlterModelTable(
            name='purchasehistory',
            table='PurchaseHistory',
        ),
    ]
