# Generated by Django 2.2 on 2022-01-29 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shops', '0012_auto_20220129_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotions',
            name='description',
            field=models.TextField(blank=True, db_index=True, max_length=40, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='description',
            field=models.TextField(blank=True, db_index=True, max_length=40, null=True, verbose_name='Описание'),
        ),
    ]
