# Generated by Django 2.2 on 2022-01-28 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_shops', '0003_profile_creadet_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilephotos',
            name='photo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_shops.Profile', verbose_name='Пользователь фотки'),
        ),
    ]
