# Generated by Django 2.2 on 2022-01-29 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shops', '0006_auto_20220129_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='balance',
            field=models.IntegerField(blank=True, db_index=True, default=0, max_length=100, verbose_name='Баланс'),
        ),
    ]
