# Generated by Django 2.2 on 2022-01-29 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_shops', '0010_auto_20220129_1903'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_product', models.CharField(db_index=True, max_length=50, null=True, verbose_name='Название товара')),
                ('price', models.IntegerField(db_index=True, null=True, verbose_name='Цена')),
                ('creadet_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='Дата покупки')),
                ('user_history', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_shops.Profile', verbose_name='История покупок пользователя')),
            ],
        ),
    ]
