# Generated by Django 2.2 on 2022-01-29 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shops', '0015_auto_20220129_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotions',
            name='active',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Активация Предложения'),
        ),
        migrations.AddField(
            model_name='stock',
            name='active',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Активация акции'),
        ),
    ]
