# Generated by Django 2.2 on 2022-01-30 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shops', '0016_auto_20220129_2354'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchasehistory',
            options={'verbose_name': 'История с товара', 'verbose_name_plural': 'истории с товарами'},
        ),
        migrations.AddField(
            model_name='purchasehistory',
            name='count_product',
            field=models.IntegerField(db_index=True, null=True, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='promotions',
            name='active',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Статус акции'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='active',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Статус акции'),
        ),
    ]
