# Generated by Django 4.0.2 on 2022-02-07 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Housing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='имя жилья')),
                ('description', models.TextField(blank=True, verbose_name='описания жилья')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Жильё',
                'verbose_name_plural': 'Жильёшки',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='заголовок')),
                ('text', models.TextField(null=True, verbose_name='текст новости')),
                ('is_published', models.BooleanField(default=False, verbose_name='опубликовать')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'новость',
                'verbose_name_plural': 'новости',
            },
        ),
        migrations.CreateModel(
            name='TypeHousing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='тип помещения')),
                ('description', models.TextField(blank=True, verbose_name='описание помещения')),
                ('hous', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_sale_home.housing', verbose_name='в каком доме')),
            ],
            options={
                'verbose_name': 'Тип жилья',
                'verbose_name_plural': 'Типы жилья',
            },
        ),
        migrations.CreateModel(
            name='NumberRooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rooms_count', models.IntegerField(default=0, verbose_name='количество комнат')),
                ('hous', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_sale_home.housing', verbose_name='в каком доме')),
            ],
            options={
                'verbose_name': 'Количество комнат',
                'verbose_name_plural': 'Количество комнат',
            },
        ),
    ]
