# Generated by Django 2.2 on 2022-01-15 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='My_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=30, verbose_name='Имя')),
                ('password', models.CharField(db_index=True, max_length=20, verbose_name='Пароль')),
                ('first_name', models.CharField(db_index=True, max_length=20, verbose_name='Фамилия')),
                ('second_name', models.CharField(db_index=True, max_length=20, verbose_name='Отчество')),
                ('email', models.EmailField(db_index=True, max_length=254, verbose_name='mail')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('is_active_user', models.BooleanField(db_index=True, verbose_name='актив')),
            ],
            options={
                'db_table': 'users',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='MyNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titlenews', models.CharField(db_index=True, max_length=200, verbose_name='Заголовок новости')),
                ('description', models.TextField(db_index=True, default='', verbose_name='описание')),
                ('created_news', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_news', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата обновления')),
                ('is_active_news', models.BooleanField(choices=[(True, 'Активно'), (False, 'Не активно')], db_index=True, default=False, verbose_name='Активность новости')),
            ],
            options={
                'db_table': 'News',
                'ordering': ['-updated_news'],
            },
        ),
        migrations.CreateModel(
            name='MyComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Имя')),
                ('description', models.TextField(db_index=True, default='', verbose_name='описание')),
                ('old_description', models.TextField(db_index=True, default='', verbose_name='Хранения комментария после удаления')),
                ('created_comments', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('city', models.CharField(db_index=True, default='Неизвестно', max_length=50, verbose_name='Город')),
                ('nickname', models.CharField(db_index=True, default='Неизвестно', max_length=50, verbose_name='Прозвище')),
                ('status_comment', models.BooleanField(choices=[(True, 'Удалено администратором'), (False, 'Комментарий норм')], db_index=True, default=False, verbose_name='статус')),
                ('id_news_current', models.IntegerField(default=0)),
                ('comment', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='app_news.MyNews', verbose_name='Название новости')),
                ('user_comments', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auther_user', to='app_news.My_User', verbose_name='Авторизированный пользователь')),
            ],
            options={
                'db_table': 'Comments',
                'ordering': ['created_comments'],
            },
        ),
    ]
