# Generated by Django 2.2 on 2022-01-17 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mynews',
            name='teg',
            field=models.CharField(choices=[('не выбрано', 'не выбрано'), ('работа', 'работа'), ('машины', 'машины'), ('спорт', 'спорт'), ('игры', 'игры')], db_index=True, default='не выбрано', max_length=100, verbose_name='ТЭГ новости'),
        ),
    ]
