# Generated by Django 2.2 on 2022-01-18 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0002_mynews_teg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mynews',
            name='teg',
            field=models.CharField(db_index=True, default='не выбрано', max_length=100, verbose_name='ТЭГ новости'),
        ),
    ]
