# Generated by Django 4.0.2 on 2022-02-03 20:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=30, null=True, verbose_name='название магазина')),
                ('adress', models.CharField(db_index=True, max_length=30, null=True, verbose_name='адрес')),
                ('tel', models.IntegerField(db_index=True, null=True, verbose_name='телефон')),
            ],
            options={
                'verbose_name': 'магазин',
                'verbose_name_plural': 'магазины',
                'db_table': 'Shops',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('Мужской', 'Мужской'), ('Женский', 'Женский')], db_index=True, default='Мужской', max_length=100, verbose_name='Выберите пол')),
                ('avatar', models.ImageField(db_index=True, null=True, upload_to='avatars/', verbose_name='Выберите файл')),
                ('creadet_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='Дата создания')),
                ('phone', models.CharField(blank=True, db_index=True, default='', max_length=15, verbose_name='Телефон')),
                ('balance', models.IntegerField(blank=True, db_index=True, default=0, verbose_name='Баланс')),
                ('status_profile', models.CharField(choices=[('новичек', 'новичек'), ('продвинутый', 'продвинутый'), ('эксперт', 'эксперт'), ('БОГ покупок', 'БОГ покупок')], db_index=True, default='новичек', max_length=100, verbose_name='Ваш статус профиля')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'профиль',
                'verbose_name_plural': 'профили',
                'db_table': 'Profile',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=30, null=True, verbose_name='название товара')),
                ('description', models.TextField(blank=True, db_index=True, null=True, verbose_name='описание товара')),
                ('price', models.FloatField(db_index=True, default=0, verbose_name='Цена')),
                ('amount_item', models.IntegerField(db_index=True, default=0, verbose_name='количество товара на складе')),
                ('count_pay', models.IntegerField(db_index=True, default=0, verbose_name='количество товара купить')),
                ('category_item', models.CharField(choices=[('еда', 'еда'), ('техника', 'техника'), ('другое', 'другое')], db_index=True, default='другое', max_length=50, verbose_name='Выберите категорию товара')),
                ('shops', models.ManyToManyField(db_index=True, to='app_shop.Shops', verbose_name='Магазины в которых эти товары')),
            ],
            options={
                'verbose_name': 'товар',
                'verbose_name_plural': 'товары',
                'db_table': 'Item',
            },
        ),
    ]
