# Generated by Django 4.0.2 on 2022-02-03 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_user', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app_shop.profile', verbose_name='Пользователь для этой корзины')),
                ('items', models.ManyToManyField(blank=True, db_index=True, null=True, to='app_shop.Item', verbose_name='Товары которые добавим в корзину')),
            ],
            options={
                'verbose_name': 'корзина',
                'verbose_name_plural': 'корзины',
                'db_table': 'ShoppingCart',
            },
        ),
    ]
