# Generated by Django 4.0.2 on 2022-02-03 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0002_shoppingcart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(db_index=True, null=True, upload_to='avatars/', verbose_name='Фото аватарки'),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='items',
            field=models.ManyToManyField(blank=True, db_index=True, to='app_shop.Item', verbose_name='Товары которые добавим в корзину'),
        ),
    ]
