# Generated by Django 4.0.2 on 2022-02-04 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0003_alter_profile_avatar_alter_shoppingcart_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='count_cart',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
