# Generated by Django 4.0.2 on 2022-02-04 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0004_profile_count_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='count_cart',
        ),
    ]
