# Generated by Django 4.0.2 on 2022-02-04 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0005_remove_profile_count_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='score',
            field=models.FloatField(blank=True, db_index=True, default=0, verbose_name='Очки профиля'),
        ),
    ]
