# Generated by Django 4.0.2 on 2022-02-04 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0007_alter_item_count_pay_productreport'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productreport',
            options={'verbose_name': 'отчет о проданных товарах', 'verbose_name_plural': 'отчеты о проданных товарах'},
        ),
        migrations.AlterField(
            model_name='productreport',
            name='product',
            field=models.ManyToManyField(blank=True, db_index=True, to='app_shop.Item', verbose_name='Проданные товары'),
        ),
        migrations.AlterModelTable(
            name='productreport',
            table='ProductReport',
        ),
    ]
