# Generated by Django 4.0.2 on 2022-02-04 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_shop', '0008_alter_productreport_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productreport',
            name='product',
        ),
        migrations.AddField(
            model_name='productreport',
            name='count_pay',
            field=models.IntegerField(db_index=True, default=0, verbose_name='количество товара купили'),
        ),
        migrations.AddField(
            model_name='productreport',
            name='description',
            field=models.TextField(blank=True, db_index=True, null=True, verbose_name='описание товара'),
        ),
        migrations.AddField(
            model_name='productreport',
            name='id_product',
            field=models.IntegerField(db_index=True, default=0, verbose_name='ИД товара'),
        ),
        migrations.AddField(
            model_name='productreport',
            name='name',
            field=models.CharField(db_index=True, max_length=30, null=True, verbose_name='название товара'),
        ),
        migrations.AddField(
            model_name='productreport',
            name='price',
            field=models.FloatField(db_index=True, default=0, verbose_name='Цена'),
        ),
        migrations.AddField(
            model_name='productreport',
            name='user_report',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Проданные товары этого пользователя'),
        ),
    ]
