# Generated by Django 4.0.2 on 2022-02-04 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0010_alter_shoppingcart_cart_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreport',
            name='count_pay',
            field=models.IntegerField(blank=True, db_index=True, default=0, verbose_name='количество товара купили'),
        ),
        migrations.AlterField(
            model_name='productreport',
            name='id_product',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='ИД товара'),
        ),
        migrations.AlterField(
            model_name='productreport',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=30, null=True, verbose_name='название товара'),
        ),
        migrations.AlterField(
            model_name='productreport',
            name='price',
            field=models.FloatField(blank=True, db_index=True, default=0, verbose_name='Цена'),
        ),
    ]
