# Generated by Django 4.0.2 on 2022-02-04 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0011_alter_productreport_count_pay_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreport',
            name='id_product',
            field=models.IntegerField(blank=True, db_index=True, default=0, verbose_name='ИД товара'),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='items',
            field=models.ManyToManyField(blank=True, db_index=True, to='app_shop.Item', verbose_name='Товары которые добавим в корзину'),
        ),
    ]
