# Generated by Django 4.0.2 on 2022-02-04 17:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_shop', '0012_alter_productreport_id_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreport',
            name='user_report',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Проданные товары этого пользователя'),
        ),
    ]
