# Generated by Django 4.0.2 on 2022-02-05 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0013_alter_productreport_user_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalProductSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_item', models.IntegerField(blank=True, null=True, verbose_name='id')),
                ('name_item', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название товара')),
                ('count_item', models.IntegerField(blank=True, null=True, verbose_name='Количество проданых товаров')),
            ],
            options={
                'db_table': 'TotalProductSale',
            },
        ),
    ]
