# Generated by Django 4.0.2 on 2022-02-05 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0014_totalproductsale'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TotalProductSale',
        ),
    ]
