# Generated by Django 2.2 on 2022-01-16 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0002_auto_20220115_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='flag_veryfication',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Флаг верификации'),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.IntegerField(db_index=True, default='+70000000000', verbose_name='Телефон'),
        ),
    ]
