# Generated by Django 2.2 on 2022-01-16 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0003_auto_20220117_0205'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': (('veryfication', 'Верифицировать пользователя'), ('no_veryfication', 'Убрать верификацию пользователя')), 'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
        migrations.AddField(
            model_name='profile',
            name='count_news',
            field=models.IntegerField(db_index=True, default=0, verbose_name='Количество новостей'),
        ),
    ]
