# Generated by Django 2.2 on 2022-01-16 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0004_auto_20220117_0244'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': (('veryfication', 'Верифицирован пользователя'), ('remove_veryfication', 'Убрать верификацию пользователя'), ('add_veryfication', 'Добавить верификацию пользователя')), 'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
    ]
