# Generated by Django 2.2 on 2022-01-17 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0005_auto_20220117_0249'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': (('veryfication', 'Верифицирован пользователя'), ('remove_veryfication', 'Убрать верификацию пользователя'), ('add_veryfication', 'Добавить верификацию пользователя'), ('moderator_time', 'Проверять новость и давать право на публикацию')), 'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
    ]
