# Generated by Django 2.2 on 2022-02-01 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Название книги')),
                ('isbn', models.IntegerField(verbose_name='международный стандартный книжный номер')),
                ('yearofissue', models.DateField(verbose_name='Год выпуска')),
                ('numberofpages', models.IntegerField(verbose_name='Количество страниц')),
            ],
            options={
                'db_table': 'Book',
            },
        ),
        migrations.CreateModel(
            name='AuthorBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='имя')),
                ('lastname', models.CharField(max_length=40, verbose_name='фамилия')),
                ('yearofbirth', models.DateField(verbose_name='Дата рождения')),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rest.Book', verbose_name='Книги')),
            ],
            options={
                'db_table': 'AuthorBook',
            },
        ),
    ]
