# Generated by Django 2.2 on 2022-01-15 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_employment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=50, verbose_name='Заголовок')),
                ('creatde_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('publisher_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Дата публикации')),
                ('description', models.TextField(db_index=True, default='', verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Резюме',
                'verbose_name_plural': 'Все резюме',
                'permissions': (('Can add', 'Может создавать'), ('Can change', 'Может редактировать'), ('Can delete', 'Может удалять'), ('Can view', 'Может просматривать')),
            },
        ),
    ]
