# Generated by Django 2.2 on 2022-01-15 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_employment', '0003_auto_20220115_2315'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='summary',
            options={'verbose_name': 'Резюме', 'verbose_name_plural': 'Все резюме'},
        ),
    ]
