# Generated by Django 2.2 on 2022-01-01 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0004_auto_20220101_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_active_user',
            field=models.BooleanField(db_index=True, default=False, verbose_name='mail'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(db_index=True, default='----', max_length=20, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='user',
            name='second_name',
            field=models.CharField(db_index=True, default='----', max_length=20, verbose_name='Отчество'),
        ),
    ]
