# Generated by Django 2.2 on 2022-01-01 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0006_auto_20220102_0032'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleNews', models.CharField(db_index=True, max_length=200, verbose_name='Заголовок новости')),
                ('description', models.TextField(db_index=True, default='', verbose_name='описание')),
                ('created_news', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_news', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата обновления')),
                ('is_active_news', models.BooleanField(db_index=True, verbose_name='Активность новости')),
            ],
            options={
                'db_table': 'News',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active_user',
            field=models.BooleanField(db_index=True, verbose_name='актив'),
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Имя')),
                ('description', models.TextField(db_index=True, default='', verbose_name='описание')),
                ('news', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='News', to='app_news.News', verbose_name='новость')),
            ],
            options={
                'db_table': 'Comments',
                'ordering': ['news'],
            },
        ),
    ]
