# Generated by Django 2.2 on 2022-01-01 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0007_auto_20220102_0219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(db_index=True, max_length=30, verbose_name='Имя'),
        ),
    ]
