# Generated by Django 2.2 on 2022-01-01 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0008_auto_20220102_0252'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='MyComments',
        ),
        migrations.RenameModel(
            old_name='News',
            new_name='MyNews',
        ),
    ]
