# Generated by Django 2.2 on 2022-01-02 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0009_auto_20220102_0256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mynews',
            old_name='titleNews',
            new_name='titlenews',
        ),
    ]
