# Generated by Django 2.2 on 2022-01-02 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0011_auto_20220102_0344'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mynews',
            options={'ordering': ['updated_news']},
        ),
    ]
