# Generated by Django 2.2 on 2022-01-02 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0012_auto_20220102_1434'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mynews',
            options={'ordering': ['-updated_news']},
        ),
    ]
