# Generated by Django 2.2 on 2022-01-02 11:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0013_auto_20220102_1436'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mycomments',
            options={'ordering': ['created_comments']},
        ),
        migrations.RemoveField(
            model_name='mycomments',
            name='news',
        ),
        migrations.AddField(
            model_name='mycomments',
            name='created_comments',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mynews',
            name='comment',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='app_news.MyComments', verbose_name='Коментарии'),
        ),
    ]
