# Generated by Django 2.2 on 2022-01-02 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0014_auto_20220102_1454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mynews',
            name='comment',
        ),
        migrations.AddField(
            model_name='mycomments',
            name='comment_news',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news', to='app_news.MyNews', verbose_name='Коментарий к новости'),
        ),
    ]
