# Generated by Django 2.2 on 2022-01-02 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0018_mynews_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mynews',
            name='comment',
        ),
        migrations.AddField(
            model_name='mycomments',
            name='comment',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='app_news.MyNews', verbose_name='новость'),
        ),
    ]
