# Generated by Django 2.2 on 2022-01-02 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0019_auto_20220102_1546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mycomments',
            name='comment',
        ),
        migrations.AddField(
            model_name='mynews',
            name='comment',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='app_news.MyComments', verbose_name='Имя коментатора'),
        ),
    ]
