# Generated by Django 2.2 on 2022-01-02 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0021_auto_20220102_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycomments',
            name='id_news',
            field=models.IntegerField(default=0),
        ),
    ]
