# Generated by Django 2.2 on 2022-01-02 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0022_mycomments_id_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='mynews',
            name='comments_users',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_user', to='app_news.MyComments', verbose_name='Имя кто написал комент'),
        ),
    ]
