# Generated by Django 2.2 on 2022-01-02 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0023_mynews_comments_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mycomments',
            name='id_news',
        ),
    ]
