# Generated by Django 2.2 on 2022-01-02 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0024_remove_mycomments_id_news'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mynews',
            name='comments_users',
        ),
    ]
