# Generated by Django 2.2 on 2022-01-02 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0025_remove_mynews_comments_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycomments',
            name='id_news_current',
            field=models.IntegerField(default=0),
        ),
    ]
