# Generated by Django 2.2 on 2022-01-03 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0026_mycomments_id_news_current'),
    ]

    operations = [
        migrations.AddField(
            model_name='mynews',
            name='all_comment',
            field=models.ManyToManyField(to='app_news.MyComments'),
        ),
    ]
