# Generated by Django 2.2 on 2022-01-03 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0028_auto_20220104_0132'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycomments',
            name='city',
            field=models.CharField(db_index=True, default='Неизвестно', max_length=50, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='mycomments',
            name='nickname',
            field=models.CharField(db_index=True, default='Неизвестно', max_length=50, verbose_name='Прозвище'),
        ),
    ]
