# Generated by Django 2.2 on 2022-01-04 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0029_auto_20220104_0249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mynews',
            name='is_active_news',
            field=models.BooleanField(choices=[('active', True), ('deactive', False)], db_index=True, default=False, verbose_name='Активность новости'),
        ),
    ]
