# Generated by Django 2.2 on 2022-01-04 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0032_auto_20220104_0413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mynews',
            name='is_active_news',
            field=models.BooleanField(choices=[('True', 'Активно'), ('False', 'Не активно')], db_index=True, default=False, verbose_name='Активность новости'),
        ),
    ]
