# Generated by Django 2.2 on 2022-01-04 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0034_auto_20220104_0419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mynews',
            name='all_comment',
        ),
    ]
