# Generated by Django 2.2 on 2022-01-04 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0035_remove_mynews_all_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='mynews',
            name='all_comment',
            field=models.ManyToManyField(to='app_news.MyComments', verbose_name='Коментарии'),
        ),
    ]
