# Generated by Django 2.2 on 2022-01-04 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0036_mynews_all_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mynews',
            name='all_comment',
        ),
    ]
