# Generated by Django 2.2 on 2022-01-07 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0038_auto_20220104_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycomments',
            name='user_comments',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auther_user', to='app_news.User', verbose_name='Авторизированный пользователь'),
        ),
    ]
