# Generated by Django 2.2 on 2022-01-10 20:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_news', '0039_mycomments_user_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(db_index=True, max_length=20, verbose_name='Пароль')),
                ('first_name', models.CharField(db_index=True, max_length=20, verbose_name='Фамилия')),
                ('second_name', models.CharField(db_index=True, max_length=20, verbose_name='Отчество')),
                ('email', models.EmailField(db_index=True, max_length=254, verbose_name='mail')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('is_active_user', models.BooleanField(db_index=True, verbose_name='актив')),
                ('username', models.OneToOneField(max_length=30, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Имя')),
            ],
            options={
                'db_table': 'users',
                'ordering': ['created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='mycomments',
            name='user_comments',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
