# Generated by Django 2.2 on 2022-01-10 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0040_auto_20220110_2306'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='myuser',
            table='MyUser',
        ),
    ]
