# Generated by Django 2.2 on 2022-01-10 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0041_auto_20220110_2306'),
    ]

    operations = [
        migrations.CreateModel(
            name='My_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=30, verbose_name='Имя')),
                ('password', models.CharField(db_index=True, max_length=20, verbose_name='Пароль')),
                ('first_name', models.CharField(db_index=True, max_length=20, verbose_name='Фамилия')),
                ('second_name', models.CharField(db_index=True, max_length=20, verbose_name='Отчество')),
                ('email', models.EmailField(db_index=True, max_length=254, verbose_name='mail')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('is_active_user', models.BooleanField(db_index=True, verbose_name='актив')),
            ],
            options={
                'db_table': 'My_User',
                'ordering': ['created_at'],
            },
        ),
        migrations.DeleteModel(
            name='MyUser',
        ),
        migrations.AddField(
            model_name='mycomments',
            name='user_comments',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auther_user', to='app_news.My_User', verbose_name='Авторизированный пользователь'),
        ),
    ]
