# Generated by Django 2.2 on 2022-01-10 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0042_auto_20220110_2352'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='my_user',
            table='Users',
        ),
    ]
