# Generated by Django 2.2 on 2022-01-10 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0044_auto_20220110_2354'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='my_user',
            table='users',
        ),
    ]
