# Generated by Django 2.2 on 2022-01-21 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='id_item',
            field=models.CharField(max_length=100, verbose_name='id'),
        ),
    ]
