# Generated by Django 2.2 on 2022-01-22 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_goods', '0003_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='file',
            name='description',
            field=models.TextField(blank=True, db_index=True, default='', verbose_name='Описание к этому файлу'),
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(db_index=True, upload_to='files/', verbose_name='Выберите фаил'),
        ),
        migrations.AlterModelTable(
            name='file',
            table='File',
        ),
    ]
