# Generated by Django 2.2 on 2022-01-23 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0006_profile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='author',
            field=models.CharField(db_index=True, max_length=60, verbose_name='Автор блога'),
        ),
    ]
