# Generated by Django 2.2 on 2022-01-23 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0007_auto_20220123_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(db_index=True, default='', upload_to='avatars/', verbose_name='Выберите фаил'),
        ),
    ]
