# Generated by Django 2.2 on 2022-01-23 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0008_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='file_img',
            field=models.ImageField(db_index=True, default='', upload_to='img_blog/', verbose_name='Фото'),
        ),
    ]
