# Generated by Django 2.2 on 2022-01-23 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0009_blog_file_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='link_file_img',
            field=models.CharField(db_index=True, default='', max_length=300, verbose_name='Ссылка'),
        ),
    ]
