# Generated by Django 2.2 on 2022-01-23 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0010_blog_link_file_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='multi_link_file_img',
            field=models.TextField(db_index=True, default='', verbose_name='Ссылка на фото'),
        ),
    ]
