# Generated by Django 2.2 on 2022-01-23 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0011_blog_multi_link_file_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='link_file_img',
        ),
    ]
