# Generated by Django 2.2 on 2022-01-24 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0012_remove_blog_link_file_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='file_img',
        ),
        migrations.CreateModel(
            name='BlogPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_img', models.ImageField(db_index=True, default='', upload_to='img_blog/', verbose_name='Фото')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog', to='app_blog.Blog')),
            ],
        ),
    ]
