# Generated by Django 2.2 on 2022-01-25 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0019_auto_20220125_0328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.IntegerField(db_index=True, default='', verbose_name='Телефон'),
        ),
    ]
