# Generated by Django 2.2 on 2022-01-25 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0022_auto_20220125_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=models.TextField(blank=True, db_index=True, verbose_name='Описание новости'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(db_index=True, max_length=60, verbose_name='Название новости'),
        ),
    ]
