# Generated by Django 2.2 on 2022-01-28 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0023_auto_20220125_1750'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name': 'blog', 'verbose_name_plural': 'blogs'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'profile', 'verbose_name_plural': 'profiles'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(db_index=True, default='', upload_to='avatars/', verbose_name='Select file'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('Мужской', 'Мужской'), ('Женский', 'Женский')], db_index=True, default='Man', max_length=100, verbose_name='Select gender'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(db_index=True, max_length=20, verbose_name='Phone'),
        ),
    ]
