# Generated by Django 2.2 on 2022-01-28 19:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0024_auto_20220128_0210'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogphoto',
            options={'verbose_name': 'blogPhoto', 'verbose_name_plural': 'blogPhotos'},
        ),
        migrations.AlterField(
            model_name='blog',
            name='author',
            field=models.CharField(db_index=True, max_length=60, verbose_name='Author blog'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='creadet_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='creadet at'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=models.TextField(blank=True, db_index=True, verbose_name='Description blog'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='multi_link_file_img',
            field=models.TextField(db_index=True, default='', verbose_name='Link photo'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(db_index=True, max_length=60, verbose_name='Name blog'),
        ),
        migrations.AlterField(
            model_name='blogphoto',
            name='file_img',
            field=models.ImageField(db_index=True, default='', upload_to='img_blog/', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('Мужской', 'Man'), ('Женский', 'Girl')], db_index=True, default='Man', max_length=100, verbose_name='Select gender'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
