# Generated by Django 4.0.2 on 2022-02-12 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_helpdream', '0002_alter_profile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(db_index=True, default='user-avatar.svg', upload_to='avatars/', verbose_name='Выберите файл'),
        ),
    ]
