# Generated by Django 4.0.2 on 2022-02-12 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_helpdream', '0004_alter_profile_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='status',
        ),
        migrations.CreateModel(
            name='StatusImgProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(choices=[('rang0', 'Ранг 0'), ('rang1', 'Ранг 1'), ('rang2', 'Ранг 2'), ('rang3', 'Ранг 3'), ('rang4', 'Ранг 4'), ('rang5', 'Ранг 5')], default='rang0', max_length=40, verbose_name='статус')),
                ('img', models.ImageField(blank=True, db_index=True, null=True, upload_to='img_status/', verbose_name='ранг')),
                ('rang_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_helpdream.profile', verbose_name='ранг пользователя')),
            ],
        ),
    ]
