# Generated by Django 4.0.2 on 2022-02-12 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_helpdream', '0006_alter_statusimgprofile_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusimgprofile',
            name='img',
            field=models.ImageField(blank=True, db_index=True, default='zvezda0.png', upload_to='img_status/', verbose_name='ранг'),
        ),
    ]
