# Generated by Django 4.0.2 on 2022-02-12 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_helpdream', '0008_alter_statusimgprofile_rang_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusimgprofile',
            name='rang_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_helpdream.profile', verbose_name='ранг пользователя'),
        ),
    ]
