# Generated by Django 4.0.2 on 2022-02-12 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_helpdream', '0011_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusimgprofile',
            name='img',
            field=models.ImageField(blank=True, choices=[('zvezda0.png', 'Ранг 0'), ('zvezda1.png', 'Ранг 1'), ('zvezda2.png', 'Ранг 2'), ('zvezda3.png', 'Ранг 3'), ('zvezda4.png', 'Ранг 4'), ('zvezda5.png', 'Ранг 5')], db_index=True, default='zvezda0.png', upload_to='img_status/', verbose_name='ранг'),
        ),
        migrations.AlterField(
            model_name='statusimgprofile',
            name='rank',
            field=models.CharField(max_length=40, verbose_name='статус'),
        ),
    ]
