# Generated by Django 4.0.2 on 2022-02-12 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_helpdream', '0012_alter_statusimgprofile_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, db_index=True, default='user-avatar.svg', upload_to='avatars/', verbose_name='Выберите файл'),
        ),
    ]
