# Generated by Django 4.0.2 on 2022-02-12 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_helpdream', '0014_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusimgprofile',
            name='img',
            field=models.ImageField(blank=True, choices=[('img_status/zvezda0.png', 'Ранг 0'), ('img_status/zvezda1.png', 'Ранг 1'), ('img_status/zvezda2.png', 'Ранг 2'), ('img_status/zvezda3.png', 'Ранг 3'), ('img_status/zvezda4.png', 'Ранг 4'), ('img_status/zvezda5.png', 'Ранг 5')], db_index=True, default='zvezda0.png', upload_to='img_status/', verbose_name='ранг'),
        ),
    ]
