# Generated by Django 4.0.2 on 2022-02-12 22:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_helpdream', '0016_alter_statusimgprofile_rang_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusimgprofile',
            name='rank',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='статус'),
        ),
    ]
