# Generated by Django 4.0.2 on 2022-02-23 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_helpdream', '0017_alter_statusimgprofile_rank'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhoHelpMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('who_help_me', models.ManyToManyField(to='app_helpdream.Profile', verbose_name='Кто мне помог')),
            ],
        ),
        migrations.CreateModel(
            name='MeHelpYou',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('me_help_you', models.ManyToManyField(to='app_helpdream.Profile', verbose_name='Кому я помог')),
            ],
        ),
    ]
