# Generated by Django 4.0.2 on 2022-02-23 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_helpdream', '0019_alter_mehelpyou_me_help_you_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whohelpme',
            name='who_profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_helpdream.profile', verbose_name='Пользователь'),
        ),
    ]
