# Generated by Django 4.0.2 on 2022-02-23 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_helpdream', '0020_whohelpme_who_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='mehelpyou',
            name='who_profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_helpdream.profile', verbose_name='Пользователь'),
        ),
    ]
