# Generated by Django 4.0.2 on 2022-02-23 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_helpdream', '0021_mehelpyou_who_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusimgprofile',
            name='rang_profile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_helpdream.profile', verbose_name='пользователь'),
        ),
    ]
