# Generated by Django 4.0.2 on 2022-02-25 21:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_helpdream', '0022_alter_statusimgprofile_rang_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='WriteDeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=50, null=True, verbose_name='название мечты')),
                ('description', models.TextField(db_index=True, null=True, verbose_name='описание мечты')),
                ('price', models.IntegerField(blank=True, db_index=True, default=0, verbose_name='сумма на мечту')),
                ('who_dream', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Чья эта мечта')),
            ],
            options={
                'verbose_name': 'Мечта',
                'verbose_name_plural': 'Мечты пользователей',
                'db_table': 'WriteDeam',
            },
        ),
        migrations.CreateModel(
            name='ImgWriteDream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, db_index=True, null=True, upload_to='img_dreams/', verbose_name='фото')),
                ('img_dream', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_helpdream.writedeam', verbose_name='фотки')),
            ],
            options={
                'db_table': 'ImgWriteDream',
            },
        ),
    ]
