# Generated by Django 4.0.2 on 2022-02-25 21:41

import app_helpdream.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_helpdream', '0023_writedeam_imgwritedream'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imgwritedream',
            name='img',
            field=models.ImageField(blank=True, db_index=True, null=True, upload_to=app_helpdream.models.user_directory_path, verbose_name='фото'),
        ),
    ]
