# Generated by Django 4.0.2 on 2022-02-25 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_helpdream', '0024_alter_imgwritedream_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='writedeam',
            name='creadet_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='Дата создания'),
        ),
    ]
