# Generated by Django 4.0.2 on 2022-02-25 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_helpdream', '0025_writedeam_creadet_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='writedeam',
            name='dream_is_active',
            field=models.BooleanField(blank=True, db_index=True, default=True, verbose_name='мечта активна'),
        ),
        migrations.AddField(
            model_name='writedeam',
            name='dream_is_complete',
            field=models.BooleanField(blank=True, db_index=True, default=False, verbose_name='мечта завершена'),
        ),
    ]
