# Generated by Django 4.0.2 on 2022-02-25 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_helpdream', '0026_writedeam_dream_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writedeam',
            name='who_dream',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_helpdream.profile', verbose_name='Чья эта мечта'),
        ),
    ]
