# Generated by Django 4.0.2 on 2022-02-25 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_helpdream', '0027_alter_writedeam_who_dream'),
    ]

    operations = [
        migrations.AddField(
            model_name='writedeam',
            name='help_price',
            field=models.IntegerField(blank=True, db_index=True, default=0, verbose_name='Сколько собрали уже на мечту'),
        ),
    ]
