# Generated by Django 4.0.2 on 2022-02-25 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_helpdream', '0028_writedeam_help_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='writedeam',
            name='updated_dream',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата обновления'),
        ),
    ]
