# Generated by Django 4.0.2 on 2022-02-26 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_helpdream', '0032_profile_img_alter_profile_max_dream_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnoninUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Аноним', max_length=50, verbose_name='Аноним')),
                ('help_anonin_balanced', models.IntegerField(blank=True, db_index=True, default=0, verbose_name='на сколько помогли анонимы')),
            ],
        ),
    ]
