# Generated by Django 4.0.2 on 2022-02-26 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_helpdream', '0033_anoninuser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AnoninUser',
            new_name='AnonimUser',
        ),
        migrations.AlterModelOptions(
            name='anonimuser',
            options={'verbose_name': 'Аноним', 'verbose_name_plural': 'Анонимы'},
        ),
        migrations.RenameField(
            model_name='anonimuser',
            old_name='help_anonin_balanced',
            new_name='help_anonim_balanced',
        ),
        migrations.AlterModelTable(
            name='anonimuser',
            table='Anonim',
        ),
    ]
