# Generated by Django 4.0.2 on 2022-02-26 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_helpdream', '0035_anonimuser_anonim_help_you'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='place',
            field=models.IntegerField(blank=True, null=True, verbose_name='слот для расчета места в топе'),
        ),
    ]
