# Generated by Django 4.0.2 on 2022-02-26 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_helpdream', '0037_remove_anonimuser_anonim_help_you_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='whohelpme',
            options={'verbose_name': 'кто помог мне', 'verbose_name_plural': 'кто помогли мне'},
        ),
        migrations.AlterModelTable(
            name='whohelpme',
            table='WhoHelpMe',
        ),
    ]
