# Generated by Django 4.0.2 on 2022-02-26 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_helpdream', '0039_alter_whohelpme_who_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whohelpme',
            name='who_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_helpdream.profile', verbose_name='Профиль, которому помогли'),
        ),
    ]
