# Generated by Django 4.0.2 on 2022-02-26 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_helpdream', '0041_remove_whohelpme_who_profile_whohelpme_where_dream'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='whohelpme',
            options={'verbose_name': 'мечта которой помогли', 'verbose_name_plural': 'мечты которым помогли'},
        ),
    ]
