# Generated by Django 4.0.2 on 2022-02-26 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_helpdream', '0042_alter_whohelpme_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='whohelpme',
            name='who_id',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='ID помогающего'),
        ),
    ]
