# Generated by Django 4.0.2 on 2022-02-26 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_helpdream', '0043_whohelpme_who_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whohelpme',
            name='who_rank',
            field=models.CharField(blank=True, default='img_status/zvezda0.png', max_length=100, verbose_name='Ссылка на ранк'),
        ),
    ]
