# Generated by Django 4.0.2 on 2022-02-26 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_helpdream', '0044_alter_whohelpme_who_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whohelpme',
            name='who_avatar',
            field=models.CharField(blank=True, default='/ALL_DATA_FILES/avatars/user-avatar.svg', max_length=100, verbose_name='Ссылка на аву'),
        ),
        migrations.AlterField(
            model_name='whohelpme',
            name='who_rank',
            field=models.CharField(blank=True, default='/ALL_DATA_FILES/img_status/zvezda0.png', max_length=100, verbose_name='Ссылка на ранк'),
        ),
    ]
