# Generated by Django 4.0.2 on 2022-02-26 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_helpdream', '0047_alter_assistprofile_help_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writedeam',
            name='title',
            field=models.CharField(db_index=True, default='неизвестно', max_length=50, null=True, verbose_name='название мечты'),
        ),
    ]
