# Generated by Django 4.0.2 on 2022-02-26 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_helpdream', '0050_alter_assistprofile_help_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistprofile',
            name='assist_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_helpdream.profile', verbose_name='Вспомогательная таблица'),
        ),
    ]
