# Generated by Django 4.0.2 on 2022-02-26 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_helpdream', '0051_alter_assistprofile_assist_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='whohelpme',
            name='help_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_helpdream.profile', verbose_name='Профиль помощь мечта'),
        ),
        migrations.DeleteModel(
            name='AssistProfile',
        ),
    ]
