# Generated by Django 4.0.2 on 2022-02-26 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_helpdream', '0052_whohelpme_help_profile_delete_assistprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whohelpme',
            name='who_avatar',
        ),
        migrations.RemoveField(
            model_name='whohelpme',
            name='who_id',
        ),
        migrations.RemoveField(
            model_name='whohelpme',
            name='who_name',
        ),
        migrations.RemoveField(
            model_name='whohelpme',
            name='who_rank',
        ),
    ]
