# Generated by Django 4.0.2 on 2022-02-26 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_helpdream', '0053_remove_whohelpme_who_avatar_remove_whohelpme_who_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MeHelpYou',
        ),
    ]
