# Generated by Django 4.0.2 on 2022-02-26 22:12

import app_helpdream.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_helpdream', '0054_delete_mehelpyou'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.ImageField(blank=True, db_index=True, default=app_helpdream.models.Profile.choise_rank, upload_to='img_status/', verbose_name='ранг'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='rank',
            field=models.IntegerField(default=app_helpdream.models.Profile.choise_rank, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='ранк'),
        ),
    ]
