# Generated by Django 4.0.2 on 2022-02-27 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_helpdream', '0056_alter_profile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='super_status',
            field=models.BooleanField(blank=True, default=False, verbose_name='супер статус'),
        ),
    ]
