# Generated by Django 4.0.2 on 2022-02-27 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_helpdream', '0058_profile_creadet_at_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whohelpme',
            name='where_dream',
        ),
        migrations.AddField(
            model_name='writedeam',
            name='where_dream',
            field=models.ManyToManyField(blank=True, db_index=True, to='app_helpdream.WhoHelpMe', verbose_name='Профиль кто помог этой мечте'),
        ),
    ]
