# Generated by Django 4.0.2 on 2022-02-27 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_helpdream', '0062_alter_profile_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.ImageField(blank=True, db_index=True, default='ALL_DATA_FIELS/img_status/zvezda0.png', upload_to='img_status/', verbose_name='ранг'),
        ),
    ]
