# Generated by Django 4.0.2 on 2022-02-27 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_helpdream', '0065_writedeam_place_alter_profile_avatar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='creadet_at_time',
        ),
        migrations.AddField(
            model_name='writedeam',
            name='creadet_at_dream_time',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='Дата создания для расчета вермени заявки'),
        ),
    ]
