# Generated by Django 4.0.2 on 2022-02-28 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_helpdream', '0066_remove_profile_creadet_at_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whohelpme',
            name='messages',
            field=models.TextField(blank=True, db_index=True, default='', verbose_name='Сообщение при донате'),
        ),
        migrations.AlterField(
            model_name='writedeam',
            name='creadet_at_dream_time',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='Дата создания для расчета времени заявки'),
        ),
    ]
