# Generated by Django 4.0.2 on 2022-03-01 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_helpdream', '0069_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='text',
            new_name='messages',
        ),
    ]
