# Generated by Django 4.0.2 on 2022-03-01 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_helpdream', '0073_alter_comments_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='messages',
            field=models.TextField(db_index=True, null=True, verbose_name='Текст сообщения'),
        ),
    ]
