# Generated by Django 4.0.2 on 2022-03-02 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_helpdream', '0074_alter_comments_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='writedeam',
            name='days_end',
            field=models.IntegerField(blank=True, default=30, verbose_name='Сколько дней до завершения мечты'),
        ),
    ]
