# Generated by Django 4.0.2 on 2022-03-03 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_helpdream', '0075_writedeam_days_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='writedeam',
            name='dream_end_time',
            field=models.BooleanField(blank=True, db_index=True, default=False, verbose_name='Кончилось время'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Мужской', 'Мужской'), ('Женский', 'Женский')], db_index=True, default='не указан', max_length=100, verbose_name='Выберите пол'),
        ),
        migrations.AlterField(
            model_name='writedeam',
            name='price',
            field=models.IntegerField(db_index=True, default=0, null=True, verbose_name='сумма на мечту'),
        ),
    ]
