# Generated by Django 4.0.2 on 2022-03-03 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_helpdream', '0077_remove_writedeam_dream_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='whohelpme',
            name='place_number',
            field=models.IntegerField(blank=True, default=0, verbose_name='порядковый номер'),
        ),
    ]
