# Generated by Django 4.0.2 on 2022-03-03 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_helpdream', '0078_whohelpme_place_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whohelpme',
            name='place_number',
        ),
        migrations.AddField(
            model_name='profile',
            name='place_number',
            field=models.IntegerField(blank=True, default=0, verbose_name='порядковый номер для ограниченого вывода в завершенных'),
        ),
    ]
