# Generated by Django 4.0.2 on 2022-03-04 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_helpdream', '0080_remove_profile_place_number_whohelpme_place_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnonimUser',
        ),
    ]
