# Generated by Django 4.0.2 on 2022-03-06 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_helpdream', '0081_delete_anonimuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='all_info_user',
            field=models.BooleanField(blank=True, db_index=True, default=False, verbose_name='Значек что вся инфа юзера заполнена'),
        ),
    ]
