# Generated by Django 4.0.2 on 2022-03-08 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_helpdream', '0083_profile_birthday'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalBoxDream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField(blank=True, db_index=True, default=0, verbose_name='Баланс BOXDREAM')),
                ('creadet_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='Дата создания')),
                ('who_help_boxdream', models.ManyToManyField(blank=True, db_index=True, to='app_helpdream.WhoHelpMe', verbose_name='Профиль кто помог BOXDREAM')),
            ],
            options={
                'db_table': 'TotalBoxDream',
                'ordering': ['-creadet_at'],
            },
        ),
        migrations.CreateModel(
            name='BoxDreamHelp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_help_box', models.IntegerField(blank=True, db_index=True, default=0, verbose_name='Сколько денег мечта получила через BOXDREAM')),
                ('data_win_box', models.DateTimeField(db_index=True, null=True, verbose_name='Дата розыгрыша')),
                ('count_box', models.IntegerField(blank=True, default=0, verbose_name='Номер розыгрыша')),
                ('who_dream_box', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_helpdream.writedeam', verbose_name='Какой мечте помогли')),
            ],
            options={
                'db_table': 'BoxDreamHelp',
                'ordering': ['count_box'],
            },
        ),
    ]
