# Generated by Django 4.0.2 on 2022-03-11 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_helpdream', '0086_historyboxdream_windream_totalboxdream_count_win_box_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='writedeam',
            name='number_for_draw',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
