# Generated by Django 4.0.2 on 2022-03-11 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_helpdream', '0088_alter_historyboxdream_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhoHelpMeBoxDream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box_win_price', models.IntegerField(blank=True, db_index=True, default=0, verbose_name='сколько выйграл ')),
                ('avatar', models.ImageField(blank=True, db_index=True, default='avatars/ava_boxdream.png', upload_to='avatar_boxdream/', verbose_name='Аватарка_boxdream')),
                ('data_popolnenia', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='writedeam',
            name='where_dream_box',
            field=models.ManyToManyField(blank=True, db_index=True, to='app_helpdream.WhoHelpMeBoxDream', verbose_name='Профиль BOXDREAM кто помог этой мечте'),
        ),
    ]
