# Generated by Django 4.0.2 on 2022-03-11 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_helpdream', '0089_whohelpmeboxdream_writedeam_where_dream_box'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whohelpmeboxdream',
            name='avatar',
            field=models.ImageField(blank=True, db_index=True, default='avatar_boxdream/ava_boxdream.png', upload_to='avatar_boxdream/', verbose_name='Аватарка_boxdream'),
        ),
    ]
