# Generated by Django 4.0.2 on 2022-03-11 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_helpdream', '0090_alter_whohelpmeboxdream_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writedeam',
            name='title',
            field=models.CharField(db_index=True, max_length=25, null=True, verbose_name='название мечты'),
        ),
    ]
