# Generated by Django 4.0.2 on 2022-03-14 18:41

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_helpdream', '0091_alter_writedeam_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
