# Generated by Django 4.0.2 on 2022-03-14 18:46

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_helpdream', '0092_comments_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
